export const teams = [
{ slug: "argentina", name: "Argentina", confederation: "CONMEBOL" },
{ slug: "australia", name: "Australia", confederation: "AFC" },
{ slug: "belgium", name: "Belgium", confederation: "UEFA" },
{ slug: "brazil", name: "Brazil", confederation: "CONMEBOL" },
{ slug: "cameroon", name: "Cameroon", confederation: "CAF" },
{ slug: "canada", name: "Canada", confederation: "CONCACAF" },
{ slug: "croatia", name: "Croatia", confederation: "UEFA" },
{ slug: "denmark", name: "Denmark", confederation: "UEFA" },
{ slug: "ecuador", name: "Ecuador", confederation: "CONMEBOL" },
{ slug: "england", name: "England", confederation: "UEFA" },
{ slug: "france", name: "France", confederation: "UEFA" },
{ slug: "germany", name: "Germany", confederation: "UEFA" },
{ slug: "ghana", name: "Ghana", confederation: "CAF" },
{ slug: "iran", name: "Iran", confederation: "AFC" },
{ slug: "japan", name: "Japan", confederation: "AFC" },
{ slug: "mexico", name: "Mexico", confederation: "CONCACAF" },
{ slug: "morocco", name: "Morocco", confederation: "CAF" },
{ slug: "netherlands", name: "Netherlands", confederation: "UEFA" },
{ slug: "poland", name: "Poland", confederation: "UEFA" },
{ slug: "portugal", name: "Portugal", confederation: "UEFA" },
{ slug: "saudi-arabia", name: "Saudi Arabia", confederation: "AFC" },
{ slug: "senegal", name: "Senegal", confederation: "CAF" },
{ slug: "serbia", name: "Serbia", confederation: "UEFA" },
{ slug: "south-korea", name: "South Korea", confederation: "AFC" },
{ slug: "spain", name: "Spain", confederation: "UEFA" },
{ slug: "switzerland", name: "Switzerland", confederation: "UEFA" },
{ slug: "tunisia", name: "Tunisia", confederation: "CAF" },
{ slug: "united-states", name: "United States", confederation: "CONCACAF" },
{ slug: "uruguay", name: "Uruguay", confederation: "CONMEBOL" },
{ slug: "wales", name: "Wales", confederation: "UEFA" }
];
